# Generated by Django 4.2.16 on 2024-12-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auto",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="autos/"),
        ),
    ]
